// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "jitsi",
    "name": "Jitsi",
    "description": "Jitsi audio and video conferencing plugin for Mattermost.",
    "homepage_url": "https://github.com/mattermost/mattermost-plugin-jitsi",
    "support_url": "https://github.com/mattermost/mattermost-plugin-jitsi/issues",
    "release_notes_url": "https://github.com/mattermost/mattermost-plugin-jitsi/releases/tag/v2.0.0",
    "icon_path": "assets/icon.svg",
    "version": "2.1.0",
    "min_server_version": "5.2.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "JitsiSettings",
                "display_name": "",
                "type": "custom",
                "help_text": "",
                "placeholder": "",
                "default": null
            }
        ]
    }
}
`);

export default manifest;
export const id: string = manifest.id;
export const version: string = manifest.version;
