// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "jitsi",
  "name": "Jitsi",
  "description": "Jitsi audio and video conferencing plugin for Mattermost.",
  "homepage_url": "https://github.com/mattermost/mattermost-plugin-jitsi",
  "support_url": "https://github.com/mattermost/mattermost-plugin-jitsi/issues",
  "release_notes_url": "https://github.com/mattermost/mattermost-plugin-jitsi/releases/tag/v2.0.0",
  "icon_path": "assets/icon.svg",
  "version": "2.0.0",
  "min_server_version": "5.2.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "ServerType",
        "display_name": "Server:",
        "type": "radio",
        "help_text": "Select the type of jitsi server you want to use.",
        "placeholder": "",
        "default": "jitsi",
        "options": [
          {
            "display_name": "Jitsi",
            "value": "jitsi"
          },
          {
            "display_name": "JaaS",
            "value": "jaas"
          }
        ]
      },
      {
        "key": "JitsiEmbedded",
        "display_name": "Embed Jitsi video inside Mattermost:",
        "type": "bool",
        "help_text": "(Experimental) When true, Jitsi video is embedded as a floating window inside Mattermost by default. Users can override this setting with '/jitsi settings'.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JitsiCompatibilityMode",
        "display_name": "Enable Compatibility Mode:",
        "type": "bool",
        "help_text": "(Insecure) If your Jitsi server is not compatible with this plugin, include the JavaScript API hosted on your Jitsi server directly in Mattermost instead of the default API version provided by the plugin. **WARNING:** Enabling this setting can compromise the security of your Mattermost system, if your Jitsi server is not fully trusted and allows direct modification of program files. Use with caution.",
        "placeholder": "",
        "default": false
      },
      {
        "key": "JitsiURL",
        "display_name": "Jitsi Server URL:",
        "type": "text",
        "help_text": "The URL for your Jitsi server, for example https://jitsi.example.com. Defaults to https://meet.jit.si, which is the public server provided by Jitsi.",
        "placeholder": "https://meet.jit.si",
        "default": "https://meet.jit.si"
      },
      {
        "key": "JitsiNamingScheme",
        "display_name": "Jitsi Meeting Names:",
        "type": "radio",
        "help_text": "Select how meeting names are generated by default. Users can override this setting with '/jitsi settings'.",
        "placeholder": "",
        "default": "words",
        "options": [
          {
            "display_name": "Random English words in title case (e.g. PlayfulDragonsObserveCuriously)",
            "value": "words"
          },
          {
            "display_name": "UUID (universally unique identifier)",
            "value": "uuid"
          },
          {
            "display_name": "Mattermost context specific names. Combination of team name, channel name, and random text in Public and Private channels; personal meeting name in Direct and Group Message channels.",
            "value": "mattermost"
          },
          {
            "display_name": "Allow user to select meeting name",
            "value": "ask"
          }
        ]
      },
      {
        "key": "JitsiJWT",
        "display_name": "Use JWT Authentication for Jitsi:",
        "type": "bool",
        "help_text": "(Optional) If your Jitsi server uses JSON Web Tokens (JWT) for authentication, set this value to true.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JitsiAppID",
        "display_name": "App ID for JWT Authentication:",
        "type": "text",
        "help_text": "(Optional) The app ID used for authentication by the Jitsi server and JWT token generator.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JitsiAppSecret",
        "display_name": "App Secret for JWT Authentication:",
        "type": "text",
        "help_text": "(Optional) The app secret used for authentication by the Jitsi server and JWT token generator.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JitsiLinkValidTime",
        "display_name": "Meeting Link Expiry Time (minutes):",
        "type": "number",
        "help_text": "(Optional) The number of minutes from when the meeting link is created to when it becomes invalid. Minimum is 1 minute. Only applies if using JWT authentication for your Jitsi server.",
        "placeholder": "",
        "default": 30
      },
      {
        "key": "JaaSAppID",
        "display_name": "AppID for JaaS Authentication:",
        "type": "text",
        "help_text": "Specify your JaaS AppID. You can get the AppID from https://jaas.8x8.vc/#/apikeys.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JaaSApiKey",
        "display_name": "Api key ID for JaaS Authentication:",
        "type": "text",
        "help_text": "Specify your JaaS Api key ID. You can get the Api key ID from https://jaas.8x8.vc/#/apikeys.",
        "placeholder": "",
        "default": null
      },
      {
        "key": "JaaSPrivateKey",
        "display_name": "RSA Private key for JaaS Authentication:",
        "type": "longtext",
        "help_text": "Specify your JaaS private key. You can get the private key by generating an API key pair from https://jaas.8x8.vc/#/apikeys OR from https://jaas.8x8.vc/#/start-guide in the Api Key section. (NOTE: While generating the key manually make sure to set the size to be 2048 and not 4096).",
        "placeholder": "",
        "default": null
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
