name: cd
on:
  push:
    tags:
      - "v*"

jobs:
  plugin-cd:
    uses: mattermost/actions-workflows/.github/workflows/community-plugin-cd.yml@139a051e8651e6246e3764fe342297b73120e590
    secrets: inherit
